MOD = "MatchedObjectDescriptor"
MOI = "MatchedObjectId"

BASE_DESCRIPTOR_FIELDS = [
    "PositionID",
    "PositionTitle",
    "PositionLocationDisplay",
    "PositionLocation",
    "OrganizationName",
    "DepartmentName",
    "JobCategory",
    "PositionSchedule",
    "PositionOfferingType",
    "QualificationSummary",
]

EXTENDED_DESCRIPTOR_FIELDS = ["UserArea"]
EXTENSION_ADDONS = [
    "JobSummary",
    "HiringPath",
    "Relocation",
    "TotalOpenings",
    "AgencyMarketingStatement",
    "MajorDuties",
    "Education",
    "Evaluations",
    "HowToApply",
    "WhatToExpectNext",
    "RequiredDocuments",
    "OtherInformation",
    "Benefits",
    "WithinArea",
    "KeyRequirements",
    "PositionSensitivitiy",
    "TeleworkEligible",
]

BASE_SIMPLE_FIELDS = ["JobCategory", "PositionSchedule", "PositionOfferingType"]


EXTENSION_UNPACK_BRACKETED = [
    "JobSummary",
    "Relocation",
    "TotalOpenings",
    "AgencyMarketingStatement",
    "Education",
    "Evaluations",
    "HowToApply",
    "WhatToExpectNext",
    "RequiredDocuments",
    "OtherInformation",
    "Benefits",
    "WithinArea",
    "PositionSensitivitiy",
    "TeleworkEligible",
]

EXTENSION_LIST_FIELDS = ["HiringPath", "MajorDuties", "KeyRequirements"]


SEARCH_TERM = "remote"

PAGE_NUMS = 100
PAGE_RESULTS = 500


STOPWORDS = [
    "ourselves",
    "hers",
    "between",
    "yourself",
    "but",
    "again",
    "there",
    "about",
    "once",
    "during",
    "out",
    "very",
    "having",
    "with",
    "they",
    "own",
    "an",
    "be",
    "some",
    "for",
    "do",
    "its",
    "yours",
    "such",
    "into",
    "of",
    "most",
    "itself",
    "other",
    "off",
    "is",
    "s",
    "am",
    "or",
    "who",
    "as",
    "from",
    "him",
    "each",
    "the",
    "themselves",
    "until",
    "below",
    "are",
    "we",
    "these",
    "your",
    "his",
    "through",
    "don",
    "nor",
    "me",
    "were",
    "her",
    "more",
    "himself",
    "this",
    "down",
    "should",
    "our",
    "their",
    "while",
    "above",
    "both",
    "up",
    "to",
    "ours",
    "had",
    "she",
    "all",
    "no",
    "when",
    "at",
    "any",
    "before",
    "them",
    "same",
    "and",
    "been",
    "have",
    "in",
    "will",
    "on",
    "does",
    "yourselves",
    "then",
    "that",
    "because",
    "what",
    "over",
    "why",
    "so",
    "can",
    "did",
    "not",
    "now",
    "under",
    "he",
    "you",
    "herself",
    "has",
    "just",
    "where",
    "too",
    "only",
    "myself",
    "which",
    "those",
    "i",
    "after",
    "few",
    "whom",
    "t",
    "being",
    "if",
    "theirs",
    "my",
    "against",
    "a",
    "by",
    "doing",
    "it",
    "how",
    "further",
    "was",
    "here",
    "than",
    "this",
    "position",
    "the",
]


THRESHOLD = 0.5796810234573299

HIGH_CONFIDENCE = 0.95